export const FETCH_INCOME_SUCCESS = "FETCH_INCOME_SUCCESS";
export const FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS";
export const FETCH_SAVINGS_SUCCESS = "FETCH_SAVINGS_SUCCESS";
export const ADD_EXPNESE_SUCCESS = "ADD_EXPNESE_SUCCESS";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const FAILED_OPERATION = "FAILED_OPERATION";
